### ISSUE TITLE
Horizontal placement options

### ISSUE THREAD

**Issue by jiku** [jiku/react-burger-menu#1]
See `horizontal` branch (default).  
Adding this to use `react-burger-menu` in a [project](http://www.jiku.ca/again) (will replace that version once I have it working).  
Example works with `slide`, but could use a few styling fixes.

Main changes, it now uses
- `size = { width, height }`  
- `placement = { left, top, right, bottom }` (right prop won't work anymore.)
- flexbox (partly)

Not sure when/if I'll manage to do a full PR to `negomi`. A few changes are style-related and wouldn't be part of that.

Any feedback, help, etc welcome!
### TODO
- [ ] Go over changes.. because it's a mess.
- [ ] Make size from implementation override default for vertic-/horizontal (already implemented?)
- [ ] Fix all animations to work with it
- [ ] Fix tests
